GET http://localhost:3001/api/courses
###

GET http://localhost:3001/api/courses/615b7ba3db93de82751e6c24
###

DELETE http://localhost:3001/api/courses/615b68d35520e175713829af
###

POST http://localhost:3001/api/courses/
content-type: application/json

{
    "name": "General H&S Inductidwodwdwwdwdjh",
    "category": "Annual Refresher",
    "provider": "Internal",
    "duration": "30",
    "expiry": "365"
}
###

PUT http://localhost:3001/api/courses/615b7ba3db93de82751e6c24
content-type: application/json

{
    "name": "Animal Welfare AM/PM",
    "category": "Annual Refresher",
    "provider": "Internal",
    "duration": "90",
    "expiry": "365"
}