GET http://localhost:3001/api/courses
###

GET http://localhost:3001/api/courses/61539fb326e19b29022677f8
###

DELETE http://localhost:3001/api/courses/6154c2d7d1579c6abc3274db
###

POST http://localhost:3001/api/courses/
content-type: application/json

{
    "name": "General H&S Inductidwodwdwwdwdjh",
    "category": "Annual Refresher",
    "provider": "Internal",
    "duration": "30",
    "expiry": "365"
}
###

PUT http://localhost:3001/api/courses/6154c2d7d1579c6abc3274db
content-type: application/json

{
    "name": "Animal Welfare AM/PM",
    "category": "Annual Refresher",
    "provider": "Internal",
    "duration": "90",
    "expiry": "365"
}